# Generated by Django 4.0.5 on 2022-07-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='autor',
        ),
    ]
