# Generated by Django 4.0.5 on 2022-07-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cursos', '0005_remove_curso_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cursos',
                to='cursos.autor'
            ),
        ),
    ]
