# Generated by Django 4.0.5 on 2022-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
