# Generated by Django 4.0.5 on 2022-07-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_cursolikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.URLField(
                default='https://eucontador.com.br/wp-content/uploads/2019/10/Cursos-Online.png',
                max_length=1024
            ),
        ),
    ]
