# Generated by Django 4.0.5 on 2022-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_valor_padrao_imagem_de_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.URLField(max_length=1024),
        ),
    ]
